[workspace]
authors = ["Daniel Gruen <daniel.gruen@lmu.de>"]
channels = ["conda-forge"]
name = "miapbp-pixi-demo"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
jax = ">=0.7.0,<0.8"
